### ISSUE TITLE
delete deadletter and resend delete from deadletterQueue

### ISSUE THREAD

**Issue by andresparrab** [Carael/CrossBusExplorer#28]
Hello!
I was looking for a long time for a servicebus explorer for azure that would work in linux. And after testing many I found this and i absolutely love it.

I have been using the windows version and that was the only reason i could not change to work in linux because i needed that servicebusexplorer.

But there is something I am not able to do in CrossExplorer and it is the ability to remove a message from a deadletter queue or when i want to resend a dead letter there is not option to remove the deadletter from the deadletterqueue  

This will result in two deadletters messages with the same guid id but different times. and i cant delete one of them.

Please help. 
I really want to stop using windows and move to windows. And thanks for this app it really good

**Comment by Carael** [comment]
Hello @andresparrab! 

Glad to hear that. I got the same issue but with Mac - always needed Windows just to work with Azure Service Bus.

Regarding your issue. I guess you have 2 options:
- Use the resend deadletters option. This will just move every deadletters to active queue:
![image](https://github.com/Carael/CrossBusExplorer/assets/6861396/d1dfb784-319c-481c-a81c-8dd9c9371238)
- Use the messages tab, select Dead letter and instead of _Peek lock_, use the _Receive and delete option_. This will immediately remove the newest messages (top, by count) and you can view then and requeue one by one.
![image](https://github.com/Carael/CrossBusExplorer/assets/6861396/dc45ae6f-fb49-4469-99da-1e18e418cae9)

If that doesn't suits you please describe in details how it was done in Service Bus Explorer and I guess and can add it.

**Comment by andresparrab** [comment]
Hello thank you for your answer.
so if i have like say 100 deadletters and i choose Receive and delete, will it remove the letters from the deadletter queue ?
all 100 of them ?and i will have them in my local computer?
and if i send only back 1 or dead letters back to the subscription what will happen to the rest 98? will they be deleted from the queue for ever?
I have a typical example here that we usually work with with the windows service explorer.
1. We see that we have a bunch of deadletters in a subscription or topic lets say 100 to keep it simple.
2. i choose to see all 100 
3. pick the first of the to read and find out the problem.
4. then i fix the problem and resend. and it will remove from the deadletter and send to message, if everything goes well then it will be complete and disappear
5. sometimes we want to modified the payload and resend it. without make a copy, just move the updated deadletter to messages to then be processed
6. usually i make anew subscription with a filter to just "catch" this letter so i can work with , in service buss explorer i can choose to send to just a specific subscribtion: like myTestOfdeadletterSubscribtion. so it will only be sent there so i can work with it.
7. sometime we see that there is nothing we can do so I want to click on the deadletter and just remove it. 
Is this possible to do in crossExplorer? because if somehow i can achieve that , good buy windows for ever :)

Thank you in advance and i hope i not bother.

**Comment by andresparrab** [comment]
Hello! 
sorry to write after so long time, i had not  schedule queue job so i could not test some thing.

Thank you for explaining all steps.
But in step
 7.sometime we see that there is nothing we can do so I want to click on the deadletter and just remove it.
answer:
7: The feature to receive and delete message by sequence number was dropped in the https://github.com/Azure/azure-sdk-for-net/issues/15097 so that's not possible. You can just take the newest - and that's in my opinion how proper queueing mechanism should work. In order to remove all you can use the purge function:

I quiete did not understand that one.. so the possibility to just rigth click and delete is not possible like this?
![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/895873d0-4569-4302-8c1e-50b3fa27af5a)

Because sometime lets say i retrieve 100 in peak mode and 10 of tghem are the same guid(same dead letter that some how come again and aging. so I want just to remove 9 of the copies from the  100 i retrieved. and just keep the one of them to work with. like you see in the screenshot



Also another thing if i retrieve 100 of them and just wan to send 1 to make sure it went well .then work with next and so on without send all 100 all the time? like the screeshot below:
![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/11b7f78f-347d-46c6-9c1f-12b9a158f485)

**Comment by Carael** [comment]
I will double check this in the upcoming week.

**Comment by Carael** [comment]
In the version 0.4.1 I've added the delete button for peeked messages. It's sadly limited to only the first 250 messages (api limitation). But anyway it's there:
![image](https://github.com/Carael/CrossBusExplorer/assets/6861396/1ae5a80a-676f-4174-ba8a-76d91ddf4423)

Let me know if this help in your case.
