### ISSUE TITLE
When resending a message it convert all properties to strings and i get Operator '==' cannot be applied to operands of type 'string' and 'long'

### ISSUE THREAD

**Issue by andresparrab** [Carael/CrossBusExplorer#37]
Hello!

I have discover something that i hope you maybe can help me with as this is a mayor problem and i cant work with crossexplorer if icant find a solution to this.

Scenario:
i have a message i want to resend. 
In the windows service bus explorer i resend and all the properties are sent as they where:
Example:
orderNumber 23434 (is an int)
isCancel True ( is bollean)
guid fadf343-3454fff-565g  (string)

but when i send the same message in the crossexplorer all properties get converted into strings.
So every topic that are listening to a certain type will get error as is expected to be an int or boolean or something but get strings.

I tried to make the screenshots to show the problem mentioned and i hope maybe there a way to send the messages with all properties types as the one in windows?

![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/4ba37e0a-50d5-477b-b3c9-089dfa15a4c4)
![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/04478926-0f98-4883-b6f7-eb4cf4c7e8ce)
![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/3618b3c6-240d-4715-a3ae-f40884e4e4d2)

**Comment by Carael** [comment]
Ok now by default all values are converted into strings - the type information is lost while sending from ui. I will add this in next version since it's a big issue.

**Comment by andresparrab** [comment]
thank you appreciate it

**Comment by andresparrab** [comment]
Hi!
I wanted to ask if there is any release date for nex version with this fix?
For now im stuck back in usin virtualbox with windows. and almoste overheating laptop :)

**Comment by Carael** [comment]
Done in release 0.4.0
