### ISSUE TITLE
When resending message Bool does cast error

### ISSUE THREAD

**Issue by andresparrab** [Carael/CrossBusExplorer#42]
Hello!
Thank you for the new release:
I have downloaded it and tested :

Now it looks like then sending a message with properties like int, string, Datetime works.
But not Boolean values like True or False
![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/0769832e-9f28-4cb8-a724-336f0a64761e)
![image]![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/d9d2face-9a9c-4103-950c-2692ee985f3b)

if i convert just for test purpose the Bolloena to a string then it will resend the message. 
![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/83e90a0d-412c-45ad-bfda-4fcfbd2bbde1)

![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/43cc464e-e9df-4d0e-9960-77ed692fb98b)

Also when i try to check some topics and get the messages and try to view message details i get this error:
![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/ce5cfbbd-26fb-4a78-a7c1-f4459c60259c)

I Toogle developer optiond and clean and reload . here is the output from console. I hope this helps

![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/c86be6c4-3403-4398-a82d-e9ed21c3295b)

```blazor.server.js:1 [2024-02-15T07:50:45.758Z] Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'. 
log @ blazor.server.js:1
unhandledError @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
_invokeClientMethod @ blazor.server.js:1
_processIncomingData @ blazor.server.js:1
Yt.connection.onreceive @ blazor.server.js:1
s.onmessage @ blazor.server.js:1
blazor.server.js:1 [2024-02-15T07:50:45.764Z] Information: Connection disconnected.
54blazor.server.js:1 Uncaught Error: No interop methods are registered for renderer 1
    at T (blazor.server.js:1:13936)
    at blazor.server.js:1:13842
    at D (blazor.server.js:1:14025)
    at k (blazor.server.js:1:13816)
    at P.dispatchGlobalEventToAllElements (blazor.server.js:1:16418)
    at P.onGlobalEvent (blazor.server.js:1:15611)```

**Comment by Carael** [comment]
Thanks for testing, didn't noticed this. It's fixed in 0.4.2 release.
