### ISSUE TITLE
when viewing some messages it crash

### ISSUE THREAD

**Issue by andresparrab** [Carael/CrossBusExplorer#44]
Hi thanks you for fixing the boolean problem.
Im happy to test because i went this to be my to go app for servicebuss messages. And I like this is in blazor. i learning it. maybe i can contribute to fix problems in the future

In some topics when i try to view the messages from the messages list i get a red banner and say An error has occurred, the application no longer responds. Reload

but other topics work to view messages without problem.
I have checked both topics, the one that work and the one that crash in the windows service bus explorer and both work. I just want to check that it was not an issue with the topics. to rule that out 

![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/257231c1-0d49-4361-b52d-5de5ae3f2801)

![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/66d06513-29c8-4c96-81fb-610bb6a0d799)

Here is the message of the console: 
![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/5b21fe77-6c15-4f59-ad8b-8ae25b5c219c)

**Comment by Carael** [comment]
The errors are not saying much since the error handling is not complete - it just basically states there was an unhandled exception and the application crashed. Can you maybe check pinpoint a not working message and check in the classic Service Bus Explorer what Application Properties do you have there? It may be the application property type is not supported property. In the meantime I will add global exception handler that at least logs to console the exception details.

**Comment by Carael** [comment]
Please install version 0.4.3 - this one will print detailed error message. Please then then paste this and the types of application properties as mentioned above.

**Comment by andresparrab** [comment]
I have installed 0.4.3
and i get the same error but not more logging from the console
![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/53b37975-429e-4eab-a51e-86b79eda80a7)


the screenshot for the same message below minus sensitive information . here is from windows Servicebus explorer:
![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/da02d135-207d-4e99-aacb-167abc4fd197)

i can see the message well and do everything normal.
if you need me to look something else i am available

**Comment by Carael** [comment]
I suspect in Message Custom Properties there is a type that is not supported. Can you please tell me which types are used there? I see for sure string, some numeric one (which one exactly)?

**Comment by andresparrab** [comment]
I have downloaded 0.4.5
here is the screenshot
![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/88bda5aa-e4f2-4224-a344-b45f25c263a5)

In the windows service bus in the red square can you see the Custom Properties and their values.

I dont if it is because source = null    makes the error that it cant make and instansce of the object?

![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/6b7752b2-983b-4637-b64a-c4b546737074)

**Comment by Carael** [comment]
Ok thank's for the feedback. Yes that would be for sure this and I'm able now to reproduce the error. I will look into it ASAP. Didn't think about the nullability to be honest.

**Comment by andresparrab** [comment]
> Ok thank's for the feedback. Yes that would be for sure this and I'm able now to reproduce the error. I will look into it ASAP. Didn't think about the nullability to be honest.

Is not easy to think about everything, usually is when things dont work that we find the problem. And i hapy to give feedback this will be good for both of us. I test it and report back. so in the end it will be an more Awsome app that already is. and a totally cross plattform app

**Comment by andresparrab** [comment]
anoher discovery...i think this was related to a another issue about the size of the panel to the left sio the text dont get squished
![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/3ce95850-baeb-4abe-bb44-c10d076327f6)

If remove the css max-width: 444px
then the panel look really nice
![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/8fad2b66-4f5f-4fdc-a98b-9d313329a387)

**Comment by Carael** [comment]
Pushed fix for the null messages. For the other finding I will create a separate bug.
