### ISSUE TITLE
When click Delete message nothing happens

### ISSUE THREAD

**Issue by andresparrab** [Carael/CrossBusExplorer#53]
![image](https://github.com/Carael/CrossBusExplorer/assets/60740824/69b8c8a8-2f59-4828-942b-12d2267fa44e)

When I click och the delete icon(trash can) and then yes. the message is still there. 
I refresh and get out of this subscription and back and the message still there.

Expected behaviour:

the message will be deleted from the dead letter queue.
I provided the console log but it does not display any errors or message

**Comment by Carael** [comment]
This functionality is very limited since in code I need to iterate over every earlier message, retrieve it in correct mode and complete. So the more you are at the end the slower it gets. You should see the progress indicator on the left side.

**Comment by Carael** [comment]
Indeed there was a problem with the Messages receiver. It's fixed in the release 0.4.8.
