### ISSUE TITLE
latest 4.10 crossbusexplorer-linux-snap-x64.zip is 4.9

### ISSUE THREAD

**Issue by andresparrab** [Carael/CrossBusExplorer#60]
Hi!
I have downloaded the latest [crossbusexplorer-linux-snap-x64.zip](https://github.com/Carael/CrossBusExplorer/releases/download/0.4.10/crossbusexplorer-linux-snap-x64.zip)
but when i unzip it is the previous verison 4.9

**Comment by Carael** [comment]
My bad, the build version is not automated. Forgot to change it. Released new 0.4.11.
